export const routes = {
  root: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  createProfile: '/create-profile',
  dashboard: '/app',
  dashboardCertificate: '/app/certificate',
  dashboardDocuments: '/app/documents',
  dashboardLogout: '/app/logout',
  dashboardProfileDetails: '/app/profile-details',
  dashboardSettings: '/app/settings',
  dashboardShare: '/app/invite',
  aboutUS: '/about-us',
  dataSecurity: '/data-security',
  faq: '/faq',
  imprint: '/imprint',
  landlords: '/landlords',
  privacyPolicy: '/privacy-policy',
  tenants: '/tenants',
  termsAndConditions: '/terms-and-conditions',
  landlordDashboard: '/app/landlord-dashboard',
  properties: '/app/properties',
  ambedQr: '/app/qrcode'
};
